title: Jacob's Website
author: Jacob McAleese
email: jacob.mcaleese@mail.weber.edu
description: >- # this means to ignore newlines until "baseurl:"
  I don't know what my awesome website is about yet. Thank you for coming to my Ted Talk!
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
theme: "jekyll-theme-minimal"

exclude:
  - "assets/Video"
